### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by Aa136075837** [ocwvar/DarkPurple#15]
用自己的APP控制别人的播放器上一曲，下一曲怎么实现呢？请大神指点一下

**Comment by ocwvar** [comment]
这不太现实。
你可以尝试：
1.如果它用的广域广播，你可以监听并模拟广播
2.(我没有尝试过) 你可以试试模拟mediaButton按键的上一首下一首事件的广播，但如果没办法模拟或是它的APP内部对这事件没有处理，那就无法进行控制了
